### PR TITLE
docs: remove misleading statement from github pages docs

### PR DESCRIPTION
**Pull request by VaibhavSys**

### CODE REVIEW

**Review by wdhdev — CHANGES_REQUESTED** [review]
This is a true statement.

**Comment by nullishamy** [comment]
Was going to provide these instructions to a friend (I was the one who contributed it originally so knew it was supposed to exist), and I see it's no longer published, as per this PR. Wondering what's changed about GitHub Pages to facilitate this? I haven't heard of anything changing so believe this PR should be reverted based on my current knowledge.

**Comment by wdhdev** [comment]
This is a true statement but can confuse some new users so that’s why we removed it.

**Comment by nullishamy** [comment]
Ah, I see, thanks for clarifying. No worries.

**Pull request merged**
